test

diff --git a/.github/actions/build-helm/action.yaml b/.github/actions/build-helm/action.yaml
--- a/.github/actions/build-helm/action.yaml
+++ b/.github/actions/build-helm/action.yaml
@@ -31,15 +31,20 @@ runs:
         echo "${{ inputs.secring }}" | base64 -d > ~/.gnupg/secring.gpg
         echo "${{ inputs.passphrase }}" > ~/.gnupg/passphrase
 
+        # Set up a trap to ensure cleanup even on failure
+        trap 'cleanup' ERR
+
         helm package \
           "./config/helm/chart/default/" \
           -d ${{ inputs.output-dir }} \
           --app-version "${{ inputs.version }}" \
-          --version "${{ inputs.version }}"
+          --version "${{ inputs.version }}" \
           --sign \
           --key "Dynatrace LLC" \
           --keyring ~/.gnupg/secring.gpg \
           --passphrase-file ~/.gnupg/passphrase
 
-        rm ~/.gnupg/secring.gpg
-        rm ~/.gnupg/passphrase
+        cleanup() {
+          rm -f ~/.gnupg/secring.gpg
+          rm -f ~/.gnupg/passphrase
+        }
